name: Docker CI

on:
    push:
        branches:
            - main
        paths:
            - "src/**"
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

env:
    TF_WORKING_DIR: ./src

jobs:
    Docker:
        name: Docker CI
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.TF_WORKING_DIR }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Docker Build
              uses: docker/setup-buildx-action@v3

            - name: Login To DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build and Push Image
              uses: docker/build-push-action@v6
              with:
                context: ./src
                file: ./src/Dockerfile
                push: true
                tags: |
                    jhonni1000/linux-monitoring:latest
                    jhonni1000/linux-monitoring:${{ github.sha }}
            
            - name: Verify pushed image
              run: docker pull ${{ secrets.DOCKER_USERNAME_TOKEN }}/linux-monitoring:latest